import { defineConfig } from "drizzle-kit";

// Used only for optional tooling (e.g. `drizzle-kit studio` to browse the
// database, or `npm run db:generate` if you evolve the schema later). The
// database itself is created from database/schema.sql, not from migrations
// generated by this config.
export default defineConfig({
  dialect: "postgresql",
  schema: "./server/db/schema.ts",
  out: "./drizzle",
  dbCredentials: {
    url: process.env.DATABASE_URL ?? "",
  },
});
